const base=process.env.ONE_API_URL||'http://127.0.0.1:8790';
const O={mission:'https://webmcp-one-mission.paul-phillips1988.workers.dev',broadband:'https://webmcp-one-broadband.paul-phillips1988.workers.dev',movers:'https://webmcp-one-movers.paul-phillips1988.workers.dev',energy:'https://webmcp-one-energy.paul-phillips1988.workers.dev'};
async function call(path,{method='GET',origin,body}={}){const r=await fetch(base+path,{method,headers:{...(origin?{Origin:origin}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json();return{status:r.status,data:d}}
function eq(actual,expected,label){if(actual!==expected)throw new Error(`${label}: expected ${expected}, got ${actual}`);console.log('PASS',label)}
const session=await call('/api/session',{method:'POST',origin:O.mission});eq(session.status,201,'session created');const id=session.data.mission.missionId;
const bb=await call('/api/holds/broadband',{method:'POST',origin:O.broadband,body:{missionId:id,missionVersion:1,planId:'northstar-gig',planName:'Northstar Gigabit',speedMbps:1000,monthlyPence:3400,contractMonths:24}});eq(bb.status,201,'broadband held');
const lost=await call('/api/holds/movers',{method:'POST',origin:O.movers,body:{missionId:id,missionVersion:1,slotId:'boxfox-1030',startTime:'10:30',pricePence:28900,durationHours:4}});eq(lost.status,409,'cheapest mover disappears');eq(lost.data.code,'SLOT_NO_LONGER_AVAILABLE','mover structured recovery');
const mv=await call('/api/holds/movers',{method:'POST',origin:O.movers,body:{missionId:id,missionVersion:1,slotId:'boxfox-1100',startTime:'11:00',pricePence:31900,durationHours:4}});eq(mv.status,201,'fallback mover held');
const en=await call('/api/preparations/energy',{method:'POST',origin:O.energy,body:{missionId:id,missionVersion:1,tariffId:'evergreen-eco',tariffName:'Eco Flex',annualCostPence:95750,renewablePercent:100}});eq(en.status,201,'energy prepared');
const denied=await call('/api/confirm/broadband',{method:'POST',origin:O.broadband,body:{missionId:id,missionVersion:1,resourceId:bb.data.hold.holdId,approvalToken:'nope'}});eq(denied.status,403,'confirmation blocked before approval');eq(denied.data.code,'APPROVAL_REQUIRED','approval boundary');
const approval=await call(`/api/approval/${id}`,{method:'POST',origin:O.mission});eq(approval.status,201,'human approval created');const token=approval.data.approval.approvalToken;
for(const [name,origin,path,resourceId] of [['broadband',O.broadband,'/api/confirm/broadband',bb.data.hold.holdId],['movers',O.movers,'/api/confirm/movers',mv.data.hold.holdId],['energy',O.energy,'/api/confirm/energy',en.data.preparation.preparationId]]){const r=await call(path,{method:'POST',origin,body:{missionId:id,missionVersion:1,resourceId,approvalToken:token}});eq(r.status,201,`${name} confirmed after approval`)}
const done=await call(`/api/progress/${id}`);eq(done.data.broadband.status,'confirmed','broadband final state');eq(done.data.movers.status,'confirmed','movers final state');eq(done.data.energy.status,'confirmed','energy final state');eq(done.data.approval.status,'approved','approval visible');
const edit=await call(`/api/mission/${id}`,{method:'PATCH',origin:O.mission,body:{broadbandMaxMonthlyGbp:30}});eq(edit.data.mission.missionVersion,2,'human edit increments mission');
const stale=await call(`/api/progress/${id}`);eq(stale.data.broadband.status,'stale','old broadband becomes stale');eq(stale.data.movers.status,'stale','old mover becomes stale');eq(stale.data.energy.status,'stale','old energy becomes stale');eq(stale.data.approval.status,'stale','old approval becomes stale');
const reapprove=await call(`/api/approval/${id}`,{method:'POST',origin:O.mission});eq(reapprove.status,409,'cannot approve stale provider resources');eq(reapprove.data.code,'PLAN_NOT_READY','stale resources require re-plan');
console.log('ALL API FLOW CHECKS PASS',id);

console.log('\nJUDGE CHOREOGRAPHY');
const jSession=await call('/api/session',{method:'POST',origin:O.mission});eq(jSession.status,201,'judge mission created');const jid=jSession.data.mission.missionId;
const jbb1=await call('/api/holds/broadband',{method:'POST',origin:O.broadband,body:{missionId:jid,missionVersion:1,planId:'northstar-gig',planName:'Northstar Gigabit',speedMbps:1000,monthlyPence:3400,contractMonths:24}});eq(jbb1.status,201,'judge v1 gigabit held');
const jEdit=await call(`/api/mission/${jid}`,{method:'PATCH',origin:O.mission,body:{broadbandMaxMonthlyGbp:30}});eq(jEdit.data.mission.missionVersion,2,'judge human override creates v2');
const jOld=await call('/api/holds/broadband',{method:'POST',origin:O.broadband,body:{missionId:jid,missionVersion:1,planId:'northstar-gig',planName:'Northstar Gigabit',speedMbps:1000,monthlyPence:3400,contractMonths:24}});eq(jOld.status,409,'judge old v1 action refused');eq(jOld.data.code,'MISSION_STALE','judge stale code');
const jStale=await call(`/api/progress/${jid}`);eq(jStale.data.broadband.status,'stale','judge old broadband visibly stale');
const jbb2=await call('/api/holds/broadband',{method:'POST',origin:O.broadband,body:{missionId:jid,missionVersion:2,planId:'northstar-500',planName:'Northstar 500',speedMbps:500,monthlyPence:2700,contractMonths:18}});eq(jbb2.status,201,'judge v2 broadband re-planned');
const jLost=await call('/api/holds/movers',{method:'POST',origin:O.movers,body:{missionId:jid,missionVersion:2,slotId:'boxfox-1030',startTime:'10:30',pricePence:28900,durationHours:4}});eq(jLost.data.code,'SLOT_NO_LONGER_AVAILABLE','judge moving slot disappears at v2');
const jmv=await call('/api/holds/movers',{method:'POST',origin:O.movers,body:{missionId:jid,missionVersion:2,slotId:'boxfox-1100',startTime:'11:00',pricePence:31900,durationHours:4}});eq(jmv.status,201,'judge mover recovers at v2');
const jen=await call('/api/preparations/energy',{method:'POST',origin:O.energy,body:{missionId:jid,missionVersion:2,tariffId:'evergreen-eco',tariffName:'Eco Flex',annualCostPence:95750,renewablePercent:100}});eq(jen.status,201,'judge energy prepared at v2');
const jReady=await call(`/api/progress/${jid}`);eq(jReady.data.broadband.status,'held','judge broadband current');eq(jReady.data.movers.status,'held','judge movers current');eq(jReady.data.energy.status,'prepared','judge energy current');
const jApproval=await call(`/api/approval/${jid}`,{method:'POST',origin:O.mission});eq(jApproval.status,201,'judge exact v2 plan can be approved');
console.log('JUDGE CHOREOGRAPHY PASS',jid);
