import { registerReadOnlyTool,registerTool } from '../../../packages/webmcp/src/register.js';
const API='https://webmcp-one-api.paul-phillips1988.workers.dev',missionId=new URL(location.href).searchParams.get('mission'),content=document.querySelector('[data-app-content]');
const TARIFFS=[
{id:'evergreen-standard',name:'Everyday Saver',unitPence:24.1,standingPence:52,renewablePercent:35,fixedMonths:0},
{id:'evergreen-eco',name:'Eco Flex',unitPence:25.0,standingPence:50,renewablePercent:100,fixedMonths:0},
{id:'evergreen-green-fixed',name:'Green Fixed 12',unitPence:25.4,standingPence:48,renewablePercent:100,fixedMonths:12},
{id:'evergreen-value-fixed',name:'Value Fixed 12',unitPence:24.4,standingPence:51,renewablePercent:55,fixedMonths:12}
];
let mission=null,lastComparison=null;boot().catch(fatal);
async function boot(){if(!missionId)throw new Error('This provider needs a mission. Open it from the ONE Mission Board.');mission=await api(`/api/mission/${encodeURIComponent(missionId)}`);render();await Promise.all([
registerReadOnlyTool({name:'compare_energy_tariffs',title:'Compare energy tariffs',description:'Compare Evergreen electricity tariffs using annual electricity consumption, renewable preference and the maximum acceptable annual green premium. Returns annual cost and a recommendation with a reason. This is read-only.',inputSchema:{type:'object',properties:{annual_kwh:{type:'integer',minimum:500,maximum:20000,description:'Estimated annual electricity usage in kWh'},prefer_renewable:{type:'boolean'},max_green_premium_gbp:{type:'number',minimum:0,maximum:500}},required:['annual_kwh','prefer_renewable','max_green_premium_gbp'],additionalProperties:false},execute:async i=>compare(Number(i.annual_kwh),Boolean(i.prefer_renewable),Number(i.max_green_premium_gbp),true)}),
registerTool({name:'prepare_energy_switch',title:'Prepare energy switch',description:'Prepare a reversible Evergreen tariff switch for this mission. This does not confirm or activate a contract. Requires the current mission version; stale intent is refused with MISSION_STALE.',inputSchema:{type:'object',properties:{mission_id:{type:'string'},mission_version:{type:'integer',minimum:1},tariff_id:{type:'string',enum:TARIFFS.map(t=>t.id)},annual_kwh:{type:'integer',minimum:500,maximum:20000}},required:['mission_id','mission_version','tariff_id','annual_kwh'],additionalProperties:false},execute:async i=>prepare(i,true)}),
registerTool({name:'confirm_energy_switch',title:'Confirm energy switch',description:'Complete the simulated Evergreen switch only after the human approved the prepared plan in ONE. Requires current mission version, preparation ID and ONE approval token.',inputSchema:{type:'object',properties:{mission_id:{type:'string'},mission_version:{type:'integer',minimum:1},preparation_id:{type:'string'},approval_token:{type:'string'}},required:['mission_id','mission_version','preparation_id','approval_token'],additionalProperties:false},execute:async i=>confirm(i,true)})])}
function render(){const ec=mission.constraints.energy;content.innerHTML=`<section class="provider-shell"><div class="surface provider-control"><div class="kicker">YOUR ENERGY RULES · MISSION v${mission.missionVersion}</div><h2>${esc(mission.move.to)} electricity</h2><div class="human-form"><label>Annual use<input id="kwh" type="number" min="500" max="20000" step="100" value="3100"><span>kWh</span></label><label>Green premium<input id="premium" type="number" min="0" max="500" step="5" value="${ec.maxGreenPremiumAnnualGbp}"><span>GBP/yr</span></label><label style="grid-template-columns:1fr auto"><span>Prefer renewable</span><input id="renewable" type="checkbox" ${ec.preferRenewable?'checked':''}></label><button class="primary" id="compare">Compare tariffs</button></div><p class="hint">Evergreen calculates annual cost itself. Renewable only wins when its premium stays inside the human's rule.</p></div><div class="surface results"><div class="results-head"><div><div class="kicker">EVERGREEN TARIFFS</div><h3>Annual comparison</h3></div><span data-result-count>Not compared</span></div><div data-results><div class="empty">Compare to see annual costs.</div></div></div></section>`;document.querySelector('#compare').addEventListener('click',()=>compare(Number(document.querySelector('#kwh').value),document.querySelector('#renewable').checked,Number(document.querySelector('#premium').value),false))}
function compare(kwh,preferRenewable,maxPremium,agent){if(!Number.isFinite(kwh)||kwh<500||!Number.isFinite(maxPremium)||maxPremium<0)throw new Error('Enter a valid annual use and green premium');const rows=TARIFFS.map(t=>({...t,annualCostPence:Math.round(kwh*t.unitPence+365*t.standingPence)})).sort((a,b)=>a.annualCostPence-b.annualCostPence);const cheapest=rows[0],green=rows.filter(t=>t.renewablePercent===100&&t.annualCostPence-cheapest.annualCostPence<=Math.round(maxPremium*100)).sort((a,b)=>a.annualCostPence-b.annualCostPence);const choice=preferRenewable&&green.length?green[0]:cheapest;const premium=choice.annualCostPence-cheapest.annualCostPence;lastComparison={kwh,preferRenewable,maxPremium,rows,choice};draw(agent);return{service:'Evergreen Energy',missionId,annualKwh:kwh,cheapestAnnualGbp:cheapest.annualCostPence/100,tariffs:rows.map(publicTariff),recommendation:{tariffId:choice.id,reason:choice===cheapest?'Lowest annual cost because no qualifying 100% renewable tariff was required or within the premium rule':`Cheapest 100% renewable tariff within the £${maxPremium.toFixed(0)}/year green-premium rule`,greenPremiumAnnualGbp:premium/100}}}
function draw(agent){const box=document.querySelector('[data-results]'),count=document.querySelector('[data-result-count]');const {rows,choice}=lastComparison;count.textContent=`${rows.length} tariffs`;box.innerHTML=rows.map(t=>`<article class="plan ${t.id===choice.id?'best':''}" data-tariff="${t.id}"><div><small>${t.id===choice.id?'RECOMMENDED':'AVAILABLE'}</small><h3>${esc(t.name)}</h3><p>${t.renewablePercent}% renewable · ${t.fixedMonths?t.fixedMonths+' month fixed':'Flexible'} · ${t.unitPence.toFixed(1)}p/kWh</p></div><div class="price"><strong>£${(t.annualCostPence/100).toFixed(0)}</strong><span>/year</span></div><button data-prepare="${t.id}">Prepare switch</button></article>`).join('');box.querySelectorAll('[data-prepare]').forEach(b=>b.addEventListener('click',()=>prepare({mission_id:missionId,mission_version:mission.missionVersion,tariff_id:b.dataset.prepare,annual_kwh:lastComparison.kwh},false)));if(agent)document.querySelector('.results').classList.add('agent-touched')}
async function prepare(i,agent){if(String(i.mission_id)!==missionId)return{ok:false,code:'MISSION_MISMATCH',action:'open Evergreen for the intended mission'};const tariff=TARIFFS.find(t=>t.id===i.tariff_id);if(!tariff)return{ok:false,code:'TARIFF_NOT_FOUND'};const annual=Math.round(Number(i.annual_kwh)*tariff.unitPence+365*tariff.standingPence);const r=await fetch(API+'/api/preparations/energy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId,missionVersion:Number(i.mission_version),tariffId:tariff.id,tariffName:tariff.name,annualCostPence:annual,renewablePercent:tariff.renewablePercent})}),d=await r.json();if(r.status===409&&d.code==='MISSION_STALE'){notice(`Mission changed to v${d.currentVersion}. Re-read ONE before preparing a switch.`,true);return d}if(!r.ok)throw new Error(d.message||d.code||`HTTP ${r.status}`);document.querySelectorAll('.plan').forEach(x=>x.classList.toggle('held',x.dataset.tariff===tariff.id));const card=document.querySelector(`[data-tariff="${tariff.id}"]`);if(card)installConfirmButton(card,d.preparation.preparationId);notice(`${tariff.name} prepared. No contract has been confirmed. ONE now has the receipt.`,false);if(agent)card?.classList.add('agent-touched');return{...d,nextStep:'Return to ONE. This is reversible preparation only; do not confirm a contract without explicit human approval.'}}
async function confirm(i,agent){const r=await fetch(API+'/api/confirm/energy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId:String(i.mission_id),missionVersion:Number(i.mission_version),resourceId:String(i.preparation_id),approvalToken:String(i.approval_token)})}),d=await r.json();if(!r.ok){notice(d.code==='APPROVAL_REQUIRED'?'ONE approval is required before simulated confirmation.':d.message||d.code||`HTTP ${r.status}`,true);return d}notice('Evergreen simulated switch confirmed. No real supply contract was created.',false);document.querySelectorAll('.plan').forEach(x=>x.classList.remove('held'));if(agent)document.querySelector('.results')?.classList.add('agent-touched');return d}
async function humanConfirm(preparationId){const p=await api(`/api/progress/${encodeURIComponent(missionId)}`);if(p.approval?.status!=='approved'){notice('Approve the prepared plan in ONE first.',true);return}await confirm({mission_id:missionId,mission_version:p.mission.missionVersion,preparation_id:preparationId,approval_token:p.approval.approvalToken},false)}
function installConfirmButton(card,preparationId){const old=card.querySelector('button'),b=document.createElement('button');b.textContent='Confirm after ONE approval';b.addEventListener('click',()=>humanConfirm(preparationId));old.replaceWith(b)}
function publicTariff(t){return{tariffId:t.id,name:t.name,annualCostGbp:t.annualCostPence/100,renewablePercent:t.renewablePercent,unitPence:t.unitPence,standingPence:t.standingPence,fixedMonths:t.fixedMonths}}
function notice(t,e){let n=document.querySelector('[data-notice]');if(!n){n=document.createElement('div');n.dataset.notice='';n.className='notice';document.querySelector('.provider-shell').prepend(n)}n.textContent=t;n.dataset.error=e?'1':'0'}async function api(path){const r=await fetch(API+path),d=await r.json();if(!r.ok)throw new Error(d.message||d.code||`HTTP ${r.status}`);return d}function fatal(e){content.innerHTML=`<div class="surface" style="padding:30px"><h2>Evergreen needs a ONE mission</h2><p>${esc(e.message)}</p><a class="primary button-link" href="https://webmcp-one-mission.paul-phillips1988.workers.dev">Open ONE Mission Board</a></div>`}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
