import { registerReadOnlyTool } from '../../../packages/webmcp/src/register.js';
const API='https://webmcp-one-api.paul-phillips1988.workers.dev';
const PROVIDERS={broadband:'https://webmcp-one-broadband.paul-phillips1988.workers.dev',movers:'https://webmcp-one-movers.paul-phillips1988.workers.dev',energy:'https://webmcp-one-energy.paul-phillips1988.workers.dev'};
let mission,missionId;const content=document.querySelector('[data-app-content]');boot().catch(fatal);
async function boot(){missionId=new URL(location.href).searchParams.get('mission')||localStorage.getItem('one:mission');if(!missionId){const c=await api('/api/session',{method:'POST'});missionId=c.mission.missionId;localStorage.setItem('one:mission',missionId);const u=new URL(location.href);u.searchParams.set('mission',missionId);history.replaceState({},'',u)}mission=await api(`/api/mission/${encodeURIComponent(missionId)}`);render();await Promise.all([
registerReadOnlyTool({name:'get_mission',title:'Get moving mission',description:'Read the current moving-house mission, version, human constraints and approval policy. Re-read this after the human changes the mission.',inputSchema:empty(),execute:async()=>{mission=await api(`/api/mission/${encodeURIComponent(missionId)}`);render();return withDirectory(mission)}}),
registerReadOnlyTool({name:'get_service_directory',title:'Get service directory',description:'Get the independent top-level provider URLs for this mission. Open each provider website before using that provider’s Site Tools.',inputSchema:empty(),execute:async()=>directory()}),
registerReadOnlyTool({name:'get_progress',title:'Get mission progress',description:'Read current cross-site progress and receipts for this mission. Use this to understand what providers have prepared or held.',inputSchema:empty(),execute:async()=>{const p=await api(`/api/progress/${encodeURIComponent(missionId)}`);progress(p);return p}})]);await refresh();setInterval(refresh,2500)}
function render(){const d=directory();content.innerHTML=`<section class="mission-grid"><div class="mission-main surface"><div class="kicker">LIVE MISSION · v${mission.missionVersion}</div><h2>${esc(mission.goal)}</h2><div class="route"><strong>${esc(mission.move.from)}</strong><span>→</span><strong>${esc(mission.move.to)}</strong><em>${esc(date(mission.move.date))}</em></div><div class="constraint-row"><div><small>Broadband</small><b>≥ ${mission.constraints.broadband.minimumMbps} Mbps</b><span>≤ £${mission.constraints.broadband.maxMonthlyGbp}/mo</span></div><div><small>Removals</small><b>After ${esc(mission.constraints.movers.earliestTime)}</b><span>Prefer ≤ £${mission.constraints.movers.preferredMaxGbp}</span></div><div><small>Energy</small><b>${mission.constraints.energy.preferRenewable?'Renewable preferred':'Best value'}</b><span>Green premium ≤ £${mission.constraints.energy.maxGreenPremiumAnnualGbp}/yr</span></div></div></div><aside class="surface control-card"><div class="kicker">HUMAN OVERRIDE</div><h3>Change the mission while your agent works.</h3><label>Broadband max / month <strong id="budget-label">£${mission.constraints.broadband.maxMonthlyGbp}</strong></label><input id="budget" type="range" min="20" max="50" step="1" value="${mission.constraints.broadband.maxMonthlyGbp}"><button class="primary" id="save-budget">Update mission</button><p class="hint">Saving increments missionVersion. Any stateful provider action planned against the old version should refuse to proceed.</p></aside></section><section class="service-grid">${card('broadband','Northstar Broadband','Find and hold the best compliant broadband plan.',d.broadband,'Ready for agent')}${card('movers','BoxFox Removals','Quote the move and recover when a slot disappears.',d.movers,'Coming next')}${card('energy','Evergreen Energy','Compare tariffs and prepare a renewable-friendly switch.',d.energy,'Coming next')}</section><section class="surface timeline"><div class="kicker">MISSION LEDGER</div><div data-progress><p class="muted">No provider actions yet.</p></div></section>`;const range=document.querySelector('#budget'),label=document.querySelector('#budget-label');range.addEventListener('input',()=>label.textContent=`£${range.value}`);document.querySelector('#save-budget').addEventListener('click',saveBudget)}
async function saveBudget(){const b=document.querySelector('#save-budget');b.disabled=true;b.textContent='Updating…';try{const r=await api(`/api/mission/${encodeURIComponent(missionId)}`,{method:'PATCH',body:JSON.stringify({broadbandMaxMonthlyGbp:Number(document.querySelector('#budget').value)})});mission=r.mission;render();await refresh();flash(`Mission updated to v${mission.missionVersion}`)}catch(e){flash(e.message,true);b.disabled=false;b.textContent='Update mission'}}
async function refresh(){try{const p=await api(`/api/progress/${encodeURIComponent(missionId)}`);mission=p.mission;progress(p)}catch(e){console.warn(e)}}
function progress(p){const el=document.querySelector('[data-progress]');if(!el)return;const held=p.receipts.find(r=>r.service==='Northstar Broadband'&&r.status==='held'),bb=document.querySelector('[data-service="broadband"] .service-state');if(bb){bb.textContent=held?'Held':'Ready for agent';bb.dataset.state=held?'held':'ready'}if(!p.receipts.length){el.innerHTML='<p class="muted">No provider actions yet. Ask your agent to start with broadband.</p>';return}el.innerHTML=p.receipts.map(r=>`<article class="receipt"><div><b>${esc(r.service)}</b><span>${esc(r.action.replaceAll('_',' '))}</span></div><strong>${esc(r.shortSummary)}</strong><small>mission v${r.missionVersion} · ${esc(new Date(r.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}))}</small></article>`).join('')}
function directory(){return{missionId,missionVersion:mission?.missionVersion,broadband:link(PROVIDERS.broadband),movers:link(PROVIDERS.movers),energy:link(PROVIDERS.energy)}}function withDirectory(m){return{...m,serviceDirectory:directory()}}function link(base){const u=new URL(base);u.searchParams.set('mission',missionId);return u.toString()}
function card(k,n,c,u,s){return`<a class="service-card" data-service="${k}" href="${esc(u)}" target="_blank" rel="noopener"><div class="service-icon">${k==='broadband'?'⌁':k==='movers'?'▣':'ϟ'}</div><div><small>${k.toUpperCase()}</small><h3>${esc(n)}</h3><p>${esc(c)}</p></div><span class="service-state" data-state="${s==='Coming next'?'next':'ready'}">${esc(s)}</span><b class="open">Open provider ↗</b></a>`}
function empty(){return{type:'object',properties:{},additionalProperties:false}}async function api(path,opt={}){const r=await fetch(API+path,{headers:{'content-type':'application/json',...(opt.headers||{})},...opt}),d=await r.json();if(!r.ok)throw new Error(d.message||d.code||`HTTP ${r.status}`);return d}function date(v){return new Date(`${v}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}function flash(t,e=false){let n=document.querySelector('.flash');if(!n){n=document.createElement('div');n.className='flash';document.body.append(n)}n.textContent=t;n.dataset.error=e?'1':'0';n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2500)}function fatal(e){content.innerHTML=`<div class="surface" style="padding:30px"><h2>Mission could not start</h2><p>${esc(e.message)}</p><button class="primary" id="fresh">Start fresh mission</button></div>`;document.querySelector('#fresh')?.addEventListener('click',()=>{localStorage.removeItem('one:mission');location.href=location.pathname})}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
