const ALLOWED=new Set([
'https://webmcp-one-mission.paul-phillips1988.workers.dev',
'https://webmcp-one-broadband.paul-phillips1988.workers.dev',
'https://webmcp-one-movers.paul-phillips1988.workers.dev',
'https://webmcp-one-energy.paul-phillips1988.workers.dev']);
const MISSION='https://webmcp-one-mission.paul-phillips1988.workers.dev';
const BROADBAND='https://webmcp-one-broadband.paul-phillips1988.workers.dev';
export default{async fetch(request,env){const u=new URL(request.url),o=request.headers.get('Origin');if(request.method==='OPTIONS')return cors(new Response(null,{status:204}),o);if(o&&!ALLOWED.has(o))return json({ok:false,code:'ORIGIN_NOT_ALLOWED'},403,o);try{
if(u.pathname==='/health')return json({ok:true,app:'api',database:!!env.DB},200,o);
if(u.pathname==='/api/session'&&request.method==='POST'){origin(o,MISSION);return json(await createSession(env.DB),201,o)}
const m=u.pathname.match(/^\/api\/mission\/([a-zA-Z0-9-]+)$/);if(m&&request.method==='GET')return json(await getMission(env.DB,m[1]),200,o);if(m&&request.method==='PATCH'){origin(o,MISSION);return json(await updateMission(env.DB,m[1],await body(request)),200,o)}
const p=u.pathname.match(/^\/api\/progress\/([a-zA-Z0-9-]+)$/);if(p&&request.method==='GET')return json(await getProgress(env.DB,p[1]),200,o);
if(u.pathname==='/api/holds/broadband'&&request.method==='POST'){origin(o,BROADBAND);const r=await createBroadbandHold(env.DB,await body(request));return json(r.body,r.status,o)}
return json({ok:false,code:'NOT_FOUND'},404,o)}catch(e){if(e instanceof HttpError)return json({ok:false,code:e.code,message:e.message},e.status,o);console.error(e);return json({ok:false,code:'INTERNAL_ERROR'},500,o)}}};
async function createSession(db){const id=`move-${crypto.randomUUID()}`,now=new Date().toISOString();await db.prepare(`INSERT INTO missions(id,version,from_label,to_label,move_date,broadband_min_mbps,broadband_max_monthly_gbp,approval_policy,updated_at,movers_earliest_time,movers_max_gbp,energy_prefer_renewable,energy_max_green_premium_gbp,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,1,'Newcastle','Gosforth','2026-09-18',500,35,'Ask before any simulated confirmation',now,'10:00',350,1,100,now).run();return{ok:true,mission:await getMission(db,id)}}
async function getMission(db,id){const r=await db.prepare('SELECT * FROM missions WHERE id=?').bind(id).first();if(!r)throw new HttpError(404,'MISSION_NOT_FOUND','Mission not found');return missionDto(r)}
async function updateMission(db,id,b){const cur=await getMission(db,id),max=Number(b.broadbandMaxMonthlyGbp),min=Number(b.broadbandMinimumMbps??cur.constraints.broadband.minimumMbps);if(!Number.isFinite(max)||max<15||max>100)throw new HttpError(400,'INVALID_BUDGET','Broadband budget must be between £15 and £100');if(!Number.isFinite(min)||min<50||min>2000)throw new HttpError(400,'INVALID_SPEED','Minimum broadband speed must be between 50 and 2000 Mbps');await db.prepare('UPDATE missions SET broadband_max_monthly_gbp=?,broadband_min_mbps=?,version=version+1,updated_at=? WHERE id=?').bind(Math.round(max),Math.round(min),new Date().toISOString(),id).run();return{ok:true,changedBy:'human',mission:await getMission(db,id)}}
async function createBroadbandHold(db,b){for(const k of ['missionId','missionVersion','planId','planName','speedMbps','monthlyPence','contractMonths'])if(b[k]===undefined||b[k]===null||b[k]==='')throw new HttpError(400,'INVALID_HOLD',`Missing ${k}`);const m=await getMission(db,String(b.missionId)),sup=Number(b.missionVersion);if(sup!==m.missionVersion)return{status:409,body:{ok:false,code:'MISSION_STALE',suppliedVersion:sup,currentVersion:m.missionVersion,action:'re-read mission before retrying'}};const speed=Number(b.speedMbps),monthly=Number(b.monthlyPence),months=Number(b.contractMonths);if(![speed,monthly,months].every(Number.isFinite)||speed<1||monthly<1||months<1)throw new HttpError(400,'INVALID_HOLD','Invalid plan values');const holdId=`bbh-${crypto.randomUUID()}`,receiptId=`rcp-${crypto.randomUUID()}`,now=new Date(),expires=new Date(now.getTime()+15*60*1000);await db.batch([
db.prepare("UPDATE broadband_holds SET status='released' WHERE mission_id=? AND status='held'").bind(m.missionId),
db.prepare('INSERT INTO broadband_holds(id,mission_id,mission_version,plan_id,status,created_at,expires_at) VALUES(?,?,?,?,?,?,?)').bind(holdId,m.missionId,m.missionVersion,String(b.planId),'held',now.toISOString(),expires.toISOString()),
db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,m.missionId,m.missionVersion,'Northstar Broadband','hold_broadband_plan','held',holdId,`${b.planName} · ${speed} Mbps · £${(monthly/100).toFixed(2)}/month · ${months} months`,monthly,null,1,JSON.stringify(['destination','minimum speed','monthly budget']),now.toISOString())]);return{status:201,body:{ok:true,hold:{holdId,missionId:m.missionId,missionVersion:m.missionVersion,planId:String(b.planId),status:'held',expiresAt:expires.toISOString()},receipt:{receiptId,service:'Northstar Broadband',action:'hold_broadband_plan',status:'held',shortSummary:`${b.planName} held at £${(monthly/100).toFixed(2)}/month`,recurringCostPence:monthly,reversible:true,dataCategoriesUsed:['destination','minimum speed','monthly budget']}}}}
async function getProgress(db,id){const mission=await getMission(db,id),receipts=await db.prepare('SELECT * FROM receipts WHERE mission_id=? ORDER BY created_at DESC LIMIT 20').bind(id).all(),holds=await db.prepare("SELECT * FROM broadband_holds WHERE mission_id=? AND status='held' ORDER BY created_at DESC LIMIT 1").bind(id).all();return{ok:true,mission,broadband:{status:holds.results?.length?'held':'not_started',hold:holds.results?.[0]||null},receipts:(receipts.results||[]).map(receiptDto)}}
function missionDto(r){return{missionId:r.id,missionVersion:Number(r.version),goal:`Move from ${r.from_label} to ${r.to_label} on ${humanDate(r.move_date)}`,move:{from:r.from_label,to:r.to_label,date:r.move_date},constraints:{broadband:{minimumMbps:Number(r.broadband_min_mbps),maxMonthlyGbp:Number(r.broadband_max_monthly_gbp),preference:'Prefer the fastest plan within the hard monthly budget; shorter contract breaks ties'},movers:{earliestTime:r.movers_earliest_time,preferredMaxGbp:Number(r.movers_max_gbp)},energy:{preferRenewable:!!r.energy_prefer_renewable,maxGreenPremiumAnnualGbp:Number(r.energy_max_green_premium_gbp)}},approvalPolicy:r.approval_policy,updatedAt:r.updated_at}}
function receiptDto(r){return{receiptId:r.id,missionId:r.mission_id,missionVersion:Number(r.mission_version),service:r.service,action:r.action,status:r.status,resourceId:r.resource_id,shortSummary:r.summary,recurringCostPence:r.recurring_cost_pence,oneOffCostPence:r.one_off_cost_pence,reversible:!!r.reversible,dataCategoriesUsed:safe(r.data_categories_json),timestamp:r.created_at}}
function safe(v){try{return JSON.parse(v)}catch{return[]}}function humanDate(v){return new Date(`${v}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}function origin(a,e){if(a&&a!==e)throw new HttpError(403,'ORIGIN_NOT_ALLOWED','This action is not available from this origin')}async function body(r){try{return await r.json()}catch{throw new HttpError(400,'INVALID_JSON','Expected a JSON request body')}}function cors(r,o){const h=new Headers(r.headers);if(o&&ALLOWED.has(o)){h.set('Access-Control-Allow-Origin',o);h.set('Vary','Origin');h.set('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type')}return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}function json(b,s=200,o){return cors(new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}}),o)}class HttpError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code}}
