const ALLOWED=new Set([
'https://webmcp-one-mission.paul-phillips1988.workers.dev',
'https://webmcp-one-broadband.paul-phillips1988.workers.dev',
'https://webmcp-one-movers.paul-phillips1988.workers.dev',
'https://webmcp-one-energy.paul-phillips1988.workers.dev']);
const MISSION='https://webmcp-one-mission.paul-phillips1988.workers.dev';
const BROADBAND='https://webmcp-one-broadband.paul-phillips1988.workers.dev';
const MOVERS='https://webmcp-one-movers.paul-phillips1988.workers.dev';
const ENERGY='https://webmcp-one-energy.paul-phillips1988.workers.dev';
export default{async fetch(request,env){const u=new URL(request.url),o=request.headers.get('Origin');if(request.method==='OPTIONS')return cors(new Response(null,{status:204}),o);if(o&&!ALLOWED.has(o))return json({ok:false,code:'ORIGIN_NOT_ALLOWED'},403,o);try{
if(u.pathname==='/health')return json({ok:true,app:'api',database:!!env.DB},200,o);
if(u.pathname==='/api/session'&&request.method==='POST'){origin(o,MISSION);return json(await createSession(env.DB),201,o)}
const m=u.pathname.match(/^\/api\/mission\/([a-zA-Z0-9-]+)$/);if(m&&request.method==='GET')return json(await getMission(env.DB,m[1]),200,o);if(m&&request.method==='PATCH'){origin(o,MISSION);return json(await updateMission(env.DB,m[1],await body(request)),200,o)}
const p=u.pathname.match(/^\/api\/progress\/([a-zA-Z0-9-]+)$/);if(p&&request.method==='GET')return json(await getProgress(env.DB,p[1]),200,o);
if(u.pathname==='/api/holds/broadband'&&request.method==='POST'){origin(o,BROADBAND);const r=await createBroadbandHold(env.DB,await body(request));return json(r.body,r.status,o)}
if(u.pathname==='/api/holds/movers'&&request.method==='POST'){origin(o,MOVERS);const r=await createMoverHold(env.DB,await body(request));return json(r.body,r.status,o)}
if(u.pathname==='/api/preparations/energy'&&request.method==='POST'){origin(o,ENERGY);const r=await createEnergyPreparation(env.DB,await body(request));return json(r.body,r.status,o)}
const ap=u.pathname.match(/^\/api\/approval\/([a-zA-Z0-9-]+)$/);if(ap&&request.method==='POST'){origin(o,MISSION);const r=await approveMission(env.DB,ap[1]);return json(r.body,r.status,o)}
if(u.pathname==='/api/confirm/broadband'&&request.method==='POST'){origin(o,BROADBAND);const r=await confirmResource(env.DB,await body(request),{table:'broadband_holds',service:'Northstar Broadband',action:'confirm_broadband_order'});return json(r.body,r.status,o)}
if(u.pathname==='/api/confirm/movers'&&request.method==='POST'){origin(o,MOVERS);const r=await confirmResource(env.DB,await body(request),{table:'mover_holds',service:'BoxFox Removals',action:'confirm_moving_booking'});return json(r.body,r.status,o)}
if(u.pathname==='/api/confirm/energy'&&request.method==='POST'){origin(o,ENERGY);const r=await confirmResource(env.DB,await body(request),{table:'energy_preparations',service:'Evergreen Energy',action:'confirm_energy_switch'});return json(r.body,r.status,o)}
return json({ok:false,code:'NOT_FOUND'},404,o)}catch(e){if(e instanceof HttpError)return json({ok:false,code:e.code,message:e.message},e.status,o);console.error(e);return json({ok:false,code:'INTERNAL_ERROR'},500,o)}}};
async function createSession(db){const id=`move-${crypto.randomUUID()}`,now=new Date().toISOString();await db.prepare(`INSERT INTO missions(id,version,from_label,to_label,move_date,broadband_min_mbps,broadband_max_monthly_gbp,approval_policy,updated_at,movers_earliest_time,movers_max_gbp,energy_prefer_renewable,energy_max_green_premium_gbp,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,1,'Newcastle','Gosforth','2026-09-18',500,35,'Ask before any simulated confirmation',now,'10:00',350,1,100,now).run();return{ok:true,mission:await getMission(db,id)}}
async function getMission(db,id){const r=await db.prepare('SELECT * FROM missions WHERE id=?').bind(id).first();if(!r)throw new HttpError(404,'MISSION_NOT_FOUND','Mission not found');return missionDto(r)}
async function updateMission(db,id,b){const cur=await getMission(db,id),max=Number(b.broadbandMaxMonthlyGbp),min=Number(b.broadbandMinimumMbps??cur.constraints.broadband.minimumMbps);if(!Number.isFinite(max)||max<15||max>100)throw new HttpError(400,'INVALID_BUDGET','Broadband budget must be between £15 and £100');if(!Number.isFinite(min)||min<50||min>2000)throw new HttpError(400,'INVALID_SPEED','Minimum broadband speed must be between 50 and 2000 Mbps');await db.prepare('UPDATE missions SET broadband_max_monthly_gbp=?,broadband_min_mbps=?,version=version+1,updated_at=? WHERE id=?').bind(Math.round(max),Math.round(min),new Date().toISOString(),id).run();return{ok:true,changedBy:'human',mission:await getMission(db,id)}}
async function createBroadbandHold(db,b){for(const k of ['missionId','missionVersion','planId','planName','speedMbps','monthlyPence','contractMonths'])if(b[k]===undefined||b[k]===null||b[k]==='')throw new HttpError(400,'INVALID_HOLD',`Missing ${k}`);const m=await getMission(db,String(b.missionId)),sup=Number(b.missionVersion);if(sup!==m.missionVersion)return{status:409,body:{ok:false,code:'MISSION_STALE',suppliedVersion:sup,currentVersion:m.missionVersion,action:'re-read mission before retrying'}};const speed=Number(b.speedMbps),monthly=Number(b.monthlyPence),months=Number(b.contractMonths);if(![speed,monthly,months].every(Number.isFinite)||speed<1||monthly<1||months<1)throw new HttpError(400,'INVALID_HOLD','Invalid plan values');const holdId=`bbh-${crypto.randomUUID()}`,receiptId=`rcp-${crypto.randomUUID()}`,now=new Date(),expires=new Date(now.getTime()+15*60*1000);await db.batch([
db.prepare("UPDATE broadband_holds SET status='released' WHERE mission_id=? AND status='held'").bind(m.missionId),
db.prepare('INSERT INTO broadband_holds(id,mission_id,mission_version,plan_id,status,created_at,expires_at) VALUES(?,?,?,?,?,?,?)').bind(holdId,m.missionId,m.missionVersion,String(b.planId),'held',now.toISOString(),expires.toISOString()),
db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,m.missionId,m.missionVersion,'Northstar Broadband','hold_broadband_plan','held',holdId,`${b.planName} · ${speed} Mbps · £${(monthly/100).toFixed(2)}/month · ${months} months`,monthly,null,1,JSON.stringify(['destination','minimum speed','monthly budget']),now.toISOString())]);return{status:201,body:{ok:true,hold:{holdId,missionId:m.missionId,missionVersion:m.missionVersion,planId:String(b.planId),status:'held',expiresAt:expires.toISOString()},receipt:{receiptId,service:'Northstar Broadband',action:'hold_broadband_plan',status:'held',shortSummary:`${b.planName} held at £${(monthly/100).toFixed(2)}/month`,recurringCostPence:monthly,reversible:true,dataCategoriesUsed:['destination','minimum speed','monthly budget']}}}}
async function createMoverHold(db,b){
for(const k of ['missionId','missionVersion','slotId','startTime','pricePence','durationHours'])if(b[k]===undefined||b[k]===null||b[k]==='')throw new HttpError(400,'INVALID_MOVER_HOLD',`Missing ${k}`);
const m=await getMission(db,String(b.missionId)),sup=Number(b.missionVersion);if(sup!==m.missionVersion)return{status:409,body:{ok:false,code:'MISSION_STALE',suppliedVersion:sup,currentVersion:m.missionVersion,action:'re-read mission before retrying'}};
const price=Number(b.pricePence),duration=Number(b.durationHours);if(!Number.isFinite(price)||price<1||!Number.isFinite(duration)||duration<1)throw new HttpError(400,'INVALID_MOVER_HOLD','Invalid slot values');
const now=new Date(),flag=await db.prepare("SELECT value FROM scenario_flags WHERE mission_id=? AND flag='mover_cheapest_lost'").bind(m.missionId).first();
if(String(b.slotId)==='boxfox-1030'){if(!flag){const receiptId=`rcp-${crypto.randomUUID()}`;await db.batch([db.prepare("INSERT INTO scenario_flags(mission_id,flag,value,updated_at) VALUES(?,'mover_cheapest_lost',1,?)").bind(m.missionId,now.toISOString()),db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,m.missionId,m.missionVersion,'BoxFox Removals','hold_moving_slot','unavailable',String(b.slotId),`${b.startTime} slot at £${(price/100).toFixed(2)} disappeared before it could be held`,null,price,0,JSON.stringify(['move route','move date','earliest time','removals budget']),now.toISOString())]);}return{status:409,body:{ok:false,code:'SLOT_NO_LONGER_AVAILABLE',slotId:String(b.slotId),startTime:String(b.startTime),currentMissionVersion:m.missionVersion,action:'quote again and choose another available slot'}};}
const holdId=`mvh-${crypto.randomUUID()}`,receiptId=`rcp-${crypto.randomUUID()}`,expires=new Date(now.getTime()+15*60*1000);await db.batch([db.prepare("UPDATE mover_holds SET status='released' WHERE mission_id=? AND status='held'").bind(m.missionId),db.prepare('INSERT INTO mover_holds(id,mission_id,mission_version,slot_id,status,created_at,expires_at) VALUES(?,?,?,?,?,?,?)').bind(holdId,m.missionId,m.missionVersion,String(b.slotId),'held',now.toISOString(),expires.toISOString()),db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,m.missionId,m.missionVersion,'BoxFox Removals','hold_moving_slot','held',holdId,`${b.startTime} moving slot · £${(price/100).toFixed(2)} · ${duration} hours`,null,price,1,JSON.stringify(['move route','move date','earliest time','removals budget']),now.toISOString())]);return{status:201,body:{ok:true,hold:{holdId,missionId:m.missionId,missionVersion:m.missionVersion,slotId:String(b.slotId),startTime:String(b.startTime),pricePence:price,status:'held',expiresAt:expires.toISOString()},receipt:{receiptId,service:'BoxFox Removals',action:'hold_moving_slot',status:'held',shortSummary:`${b.startTime} slot held at £${(price/100).toFixed(2)}`,oneOffCostPence:price,reversible:true,dataCategoriesUsed:['move route','move date','earliest time','removals budget']}}};}
async function createEnergyPreparation(db,b){
for(const k of ['missionId','missionVersion','tariffId','tariffName','annualCostPence','renewablePercent'])if(b[k]===undefined||b[k]===null||b[k]==='')throw new HttpError(400,'INVALID_ENERGY_PREPARATION',`Missing ${k}`);
const m=await getMission(db,String(b.missionId)),sup=Number(b.missionVersion);if(sup!==m.missionVersion)return{status:409,body:{ok:false,code:'MISSION_STALE',suppliedVersion:sup,currentVersion:m.missionVersion,action:'re-read mission before preparing the switch'}};
const annual=Number(b.annualCostPence),renewable=Number(b.renewablePercent);if(!Number.isFinite(annual)||annual<1||!Number.isFinite(renewable)||renewable<0||renewable>100)throw new HttpError(400,'INVALID_ENERGY_PREPARATION','Invalid tariff values');
const prepId=`enp-${crypto.randomUUID()}`,receiptId=`rcp-${crypto.randomUUID()}`,now=new Date();await db.batch([
db.prepare("UPDATE energy_preparations SET status='released' WHERE mission_id=? AND status='prepared'").bind(m.missionId),
db.prepare('INSERT INTO energy_preparations(id,mission_id,mission_version,tariff_id,status,created_at) VALUES(?,?,?,?,?,?)').bind(prepId,m.missionId,m.missionVersion,String(b.tariffId),'prepared',now.toISOString()),
db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,m.missionId,m.missionVersion,'Evergreen Energy','prepare_energy_switch','prepared',prepId,`${b.tariffName} · £${(annual/100).toFixed(2)}/year · ${renewable}% renewable`,Math.round(annual/12),null,1,JSON.stringify(['destination','annual electricity use','renewable preference','green premium limit']),now.toISOString())]);
return{status:201,body:{ok:true,preparation:{preparationId:prepId,missionId:m.missionId,missionVersion:m.missionVersion,tariffId:String(b.tariffId),status:'prepared'},receipt:{receiptId,service:'Evergreen Energy',action:'prepare_energy_switch',status:'prepared',shortSummary:`${b.tariffName} prepared at £${(annual/100).toFixed(2)}/year`,annualCostPence:annual,reversible:true,dataCategoriesUsed:['destination','annual electricity use','renewable preference','green premium limit']}}};}
async function approveMission(db,id){const m=await getMission(db,id),bb=await db.prepare("SELECT id FROM broadband_holds WHERE mission_id=? AND mission_version=? AND status='held' ORDER BY created_at DESC LIMIT 1").bind(id,m.missionVersion).first(),mv=await db.prepare("SELECT id FROM mover_holds WHERE mission_id=? AND mission_version=? AND status='held' ORDER BY created_at DESC LIMIT 1").bind(id,m.missionVersion).first(),en=await db.prepare("SELECT id FROM energy_preparations WHERE mission_id=? AND mission_version=? AND status='prepared' ORDER BY created_at DESC LIMIT 1").bind(id,m.missionVersion).first();if(!bb||!mv||!en)return{status:409,body:{ok:false,code:'PLAN_NOT_READY',missing:[!bb?'broadband':null,!mv?'movers':null,!en?'energy':null].filter(Boolean),action:'prepare all three services before asking the human to approve'}};const token=`apr-${crypto.randomUUID()}`,now=new Date().toISOString(),receiptId=`rcp-${crypto.randomUUID()}`;await db.batch([db.prepare('INSERT INTO mission_approvals(mission_id,mission_version,token,approved_at) VALUES(?,?,?,?) ON CONFLICT(mission_id) DO UPDATE SET mission_version=excluded.mission_version,token=excluded.token,approved_at=excluded.approved_at').bind(id,m.missionVersion,token,now),db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,id,m.missionVersion,'ONE Mission Control','approve_prepared_plan','approved',token,'Human approved the prepared plan for simulated confirmation',null,null,1,'[]',now)]);return{status:201,body:{ok:true,approval:{missionId:id,missionVersion:m.missionVersion,approvalToken:token,approvedAt:now},nextStep:'The agent may now use each provider confirmation tool. Any mission change invalidates this approval.'}}}
async function confirmResource(db,b,cfg){for(const k of ['missionId','missionVersion','resourceId','approvalToken'])if(b[k]===undefined||b[k]===null||b[k]==='')throw new HttpError(400,'INVALID_CONFIRMATION',`Missing ${k}`);const m=await getMission(db,String(b.missionId)),sup=Number(b.missionVersion);if(sup!==m.missionVersion)return{status:409,body:{ok:false,code:'MISSION_STALE',suppliedVersion:sup,currentVersion:m.missionVersion,action:'re-read mission and obtain fresh human approval'}};const approval=await db.prepare('SELECT mission_version,token,approved_at FROM mission_approvals WHERE mission_id=?').bind(m.missionId).first();if(!approval||Number(approval.mission_version)!==m.missionVersion||approval.token!==String(b.approvalToken))return{status:403,body:{ok:false,code:'APPROVAL_REQUIRED',currentMissionVersion:m.missionVersion,action:'return to ONE and ask the human to approve the prepared plan'}};const resource=await db.prepare(`SELECT * FROM ${cfg.table} WHERE id=? AND mission_id=?`).bind(String(b.resourceId),m.missionId).first();if(!resource)return{status:404,body:{ok:false,code:'RESOURCE_NOT_FOUND'}};if(Number(resource.mission_version)!==m.missionVersion)return{status:409,body:{ok:false,code:'RESOURCE_STALE',resourceVersion:Number(resource.mission_version),currentVersion:m.missionVersion,action:'re-plan this provider against the current mission before confirmation'}};if(resource.status==='confirmed')return{status:200,body:{ok:true,alreadyConfirmed:true,resourceId:resource.id,service:cfg.service}};if(!['held','prepared'].includes(resource.status))return{status:409,body:{ok:false,code:'RESOURCE_NOT_READY',status:resource.status}};const previous=await db.prepare('SELECT summary,recurring_cost_pence,one_off_cost_pence,data_categories_json FROM receipts WHERE mission_id=? AND service=? AND resource_id=? ORDER BY created_at DESC LIMIT 1').bind(m.missionId,cfg.service,resource.id).first(),receiptId=`rcp-${crypto.randomUUID()}`,now=new Date().toISOString();await db.batch([db.prepare(`UPDATE ${cfg.table} SET status='confirmed' WHERE id=?`).bind(resource.id),db.prepare('INSERT INTO receipts(id,mission_id,mission_version,service,action,status,resource_id,summary,recurring_cost_pence,one_off_cost_pence,reversible,data_categories_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(receiptId,m.missionId,m.missionVersion,cfg.service,cfg.action,'confirmed',resource.id,`Simulated confirmation · ${previous?.summary||cfg.service}`,previous?.recurring_cost_pence??null,previous?.one_off_cost_pence??null,0,previous?.data_categories_json||'[]',now)]);return{status:201,body:{ok:true,confirmation:{service:cfg.service,resourceId:resource.id,status:'confirmed',simulated:true,missionVersion:m.missionVersion},receipt:{receiptId,status:'confirmed',shortSummary:`${cfg.service} simulated confirmation complete`}}}}
async function getProgress(db,id){const mission=await getMission(db,id),receipts=await db.prepare('SELECT * FROM receipts WHERE mission_id=? ORDER BY created_at DESC LIMIT 40').bind(id).all(),bb=await db.prepare("SELECT * FROM broadband_holds WHERE mission_id=? ORDER BY created_at DESC LIMIT 1").bind(id).first(),mv=await db.prepare("SELECT * FROM mover_holds WHERE mission_id=? ORDER BY created_at DESC LIMIT 1").bind(id).first(),moverFlag=await db.prepare("SELECT value FROM scenario_flags WHERE mission_id=? AND flag='mover_cheapest_lost'").bind(id).first(),en=await db.prepare("SELECT * FROM energy_preparations WHERE mission_id=? ORDER BY created_at DESC LIMIT 1").bind(id).first(),ap=await db.prepare('SELECT mission_version,token,approved_at FROM mission_approvals WHERE mission_id=?').bind(id).first(),approval=ap?(Number(ap.mission_version)===mission.missionVersion?{status:'approved',missionVersion:Number(ap.mission_version),approvalToken:ap.token,approvedAt:ap.approved_at}:{status:'stale',missionVersion:Number(ap.mission_version)}):{status:'not_approved'};return{ok:true,mission,broadband:{status:bb?(Number(bb.mission_version)===mission.missionVersion?bb.status:'stale'):'not_started',hold:bb||null},movers:{status:mv?(Number(mv.mission_version)===mission.missionVersion?mv.status:'stale'):(moverFlag?'needs_recovery':'not_started'),hold:mv||null,unavailableSlotIds:moverFlag?['boxfox-1030']:[]},energy:{status:en?(Number(en.mission_version)===mission.missionVersion?en.status:'stale'):'not_started',preparation:en||null},approval,receipts:(receipts.results||[]).map(receiptDto)}}
function missionDto(r){return{missionId:r.id,missionVersion:Number(r.version),goal:`Move from ${r.from_label} to ${r.to_label} on ${humanDate(r.move_date)}`,move:{from:r.from_label,to:r.to_label,date:r.move_date},constraints:{broadband:{minimumMbps:Number(r.broadband_min_mbps),maxMonthlyGbp:Number(r.broadband_max_monthly_gbp),preference:'Prefer the fastest plan within the hard monthly budget; shorter contract breaks ties'},movers:{earliestTime:r.movers_earliest_time,preferredMaxGbp:Number(r.movers_max_gbp)},energy:{preferRenewable:!!r.energy_prefer_renewable,maxGreenPremiumAnnualGbp:Number(r.energy_max_green_premium_gbp)}},approvalPolicy:r.approval_policy,updatedAt:r.updated_at}}
function receiptDto(r){return{receiptId:r.id,missionId:r.mission_id,missionVersion:Number(r.mission_version),service:r.service,action:r.action,status:r.status,resourceId:r.resource_id,shortSummary:r.summary,recurringCostPence:r.recurring_cost_pence,oneOffCostPence:r.one_off_cost_pence,reversible:!!r.reversible,dataCategoriesUsed:safe(r.data_categories_json),timestamp:r.created_at}}
function safe(v){try{return JSON.parse(v)}catch{return[]}}function humanDate(v){return new Date(`${v}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}function origin(a,e){if(a&&a!==e)throw new HttpError(403,'ORIGIN_NOT_ALLOWED','This action is not available from this origin')}async function body(r){try{return await r.json()}catch{throw new HttpError(400,'INVALID_JSON','Expected a JSON request body')}}function cors(r,o){const h=new Headers(r.headers);if(o&&ALLOWED.has(o)){h.set('Access-Control-Allow-Origin',o);h.set('Vary','Origin');h.set('Access-Control-Allow-Methods','GET,POST,PATCH,OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type')}return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}function json(b,s=200,o){return cors(new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}}),o)}class HttpError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code}}
